server:
  port: 8083

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/api/**
          filters:
          - name: Hystrix
            args:
              name: ordercb
              fallbackUri: forward:/orderfallback
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/api/**
          filters:
          - name: Hystrix
            args:
              name: paymentcb
              fallbackUri: forward:/paymentfallback

