server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:ordersdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  cloud:
    config:
      discovery:
        enabled: true
